remove all steam-specific code to allow for reuse by other sessions

diff --git a/usr/share/gamescope-session/gamescope-session-script b/usr/share/gamescope-session/gamescope-session-script
--- a/usr/share/gamescope-session/gamescope-session-script
+++ b/usr/share/gamescope-session/gamescope-session-script
@@ -1,31 +1,31 @@
 #!/bin/bash
 
+declare -r CLIENT=$1
+declare -r CLIENT_CONFIG_DIR_USR=/usr/share/gamescope-session/sessions.d
+declare -r CLIENT_CONFIG_DIR_ETC=/etc/gamescope-sessions.d
+
+# default empty session recovery function
+short_session_recover () {
+	:
+}
+
 # Fix intel color corruption
 # might come with some performance degradation but is better than a corrupted
 # color image
 export INTEL_DEBUG=norbc
 export mesa_glthread=true
 
-# Show VRR controls in Steam
-export STEAM_GAMESCOPE_VRR_SUPPORTED=1
-
 # Some environment variables by default (taken from Deck session)
 export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
 
 # Enable Mangoapp
-export STEAM_MANGOAPP_PRESETS_SUPPORTED=1
-export STEAM_USE_MANGOAPP=1
 export MANGOHUD_CONFIGFILE=$(mktemp /tmp/mangohud.XXXXXXXX)
 
-export STEAM_USE_DYNAMIC_VRS=1
 export RADV_FORCE_VRS_CONFIG_FILE=$(mktemp /tmp/radv_vrs.XXXXXXXX)
 
 # Plop GAMESCOPE_MODE_SAVE_FILE into $XDG_CONFIG_HOME (defaults to ~/.config).
 export GAMESCOPE_MODE_SAVE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/modes.cfg"
 export GAMESCOPE_PATCHED_EDID_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/edid.bin"
-
-# Set up first time bootstrap status
-export STEAM_BOOTSTRAP_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/bootstrap.cfg"
 
 # Make path to gamescope mode save file.
 mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
@@ -37,24 +37,12 @@ mkdir -p "$(dirname "$GAMESCOPE_PATCHED_EDID_FILE")"
 touch "$GAMESCOPE_PATCHED_EDID_FILE"
 #echo "Making Gamescope patched edid at \"$GAMESCOPE_PATCHED_EDID_FILE\""
 
-# Make path to Steam bootstrap config file.
-mkdir -p "$(dirname "$STEAM_BOOTSTRAP_CONFIG")"
-touch "$STEAM_BOOTSTRAP_CONFIG"
-
-# Support for gamescope tearing with GAMESCOPE_ALLOW_TEARING atom
-export STEAM_GAMESCOPE_HAS_TEARING_SUPPORT=1
-
-# Enable tearing controls in steam
-export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
-
 # There is no way to set a color space for an NV12
 # buffer in Wayland. And the color management protocol that is
 # meant to let this happen is missing the color range...
 # So just workaround this with an ENV var that Remote Play Together
 # and Gamescope will use for now.
 export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
-
-export STEAM_GAMESCOPE_HDR_SUPPORTED=1
 
 # Initially write no_display to our config file
 # so we don't get mangoapp showing up before Steam initializes
@@ -70,61 +58,11 @@ echo "1x1" > "$RADV_FORCE_VRS_CONFIG_FILE"
 # To expose vram info from radv
 export WINEDLLOVERRIDES=dxgi=n
 
-# Workaround for steam getting killed immediatly during reboot
-export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
-
-# Workaround for steam getting killed immediatly during shutdown
-# Same idea as reboot sentinel above
-export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
-
-# Enable volume key management via steam for this session
-export STEAM_ENABLE_VOLUME_HANDLER=1
-
-# Have SteamRT's xdg-open send http:// and https:// URLs to Steam
-export SRT_URLOPEN_PREFER_STEAM=1
-
-# Disable automatic audio device switching in steam, now handled by wireplumber
-export STEAM_DISABLE_AUDIO_DEVICE_SWITCHING=1
-
-# Enable support for xwayland isolation per-game in Steam
-export STEAM_MULTIPLE_XWAYLANDS=1
-
-# We have the Mesa integration for the fifo-based dynamic fps-limiter
-export STEAM_GAMESCOPE_DYNAMIC_FPSLIMITER=1
-
-# We have NIS support
-export STEAM_GAMESCOPE_NIS_SUPPORTED=1
-
 # Don't wait for buffers to idle on the client side before sending them to gamescope
 export vk_xwayland_wait_ready=false
 
-# Let steam know it can unmount drives without superuser privileges
-export STEAM_ALLOW_DRIVE_UNMOUNT=1
-
-# We no longer need to set GAMESCOPE_EXTERNAL_OVERLAY from steam, mangoapp now does it itself
-export STEAM_DISABLE_MANGOAPP_ATOM_WORKAROUND=1
-
-# Enable horizontal mangoapp bar
-export STEAM_MANGOAPP_HORIZONTAL_SUPPORTED=1
-
-# Scaling support
-export STEAM_GAMESCOPE_FANCY_SCALING_SUPPORT=1
-
-# Color management support
-# export STEAM_GAMESCOPE_COLOR_MANAGED=1
-export STEAM_GAMESCOPE_VIRTUAL_WHITE=1
-
-# Set input method modules for Qt/GTK that will show the Steam keyboard
-export QT_IM_MODULE=steam
-export GTK_IM_MODULE=Steam
-
 # To play nice with the short term callback-based limiter for now
 export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)
-
-# Use SteamOS background if exists
-if [ -f "/usr/share/steamos/steamos.png" ] ; then
-  export STEAM_UPDATEUI_PNG_BACKGROUND=/usr/share/steamos/steamos.png
-fi
 
 ulimit -n 524288
 
@@ -133,7 +71,15 @@ if [ -f /usr/share/gamescope-session/device-quirks ]; then
   . /usr/share/gamescope-session/device-quirks
 fi
 
-# Source environment from ~/.config/environment.d with user overrides
+# Source client app specific configuration
+set -a
+for i in ${CLIENT_CONFIG_DIR_USR}/${CLIENT} ${CLIENT_CONFIG_DIR_ETC}/${CLIENT} ;
+do
+    [[ -f "${i}" ]] && . "${i}"
+done
+set +a
+
+# Source user configuration from ~/.config/environment.d
 set -a
 for i in "${HOME}"/.config/environment.d/*.conf ;
 do
@@ -169,18 +115,10 @@ else
 	echo >&2 "!! Failed to claim global gamescope stats session"
 fi
 
-# Use cursor if file exist
-if [ -z "$CURSOR_FILE" ] ; then
-    CURSOR_FILE="${HOME}/.local/share/Steam/tenfoot/resource/images/cursors/arrow.png"
-fi
 CURSOR=""
+# Use specified cursor if file exists
 if [ -f "$CURSOR_FILE" ] ; then
     CURSOR="--cursor ${CURSOR_FILE}"
-fi
-
-# Define session if not overriden
-if [ -z "$STEAMCMD" ] ; then
-    STEAMCMD="steam -gamepadui -steamos3 -steampal -steamdeck"
 fi
 
 if [ -z "$GAMESCOPECMD" ] ; then
@@ -224,17 +162,7 @@ else
     
 fi
 
-# Workaround for Steam login issue while Steam client change propagates out of Beta
-touch "${HOME}"/.steam/root/config/SteamAppData.vdf || true
-
-if [[ -f "/etc/first-boot/bootstraplinux_ubuntu12_32.tar.xz" ]] && ! grep -q "set_bootstrap=1" "$STEAM_BOOTSTRAP_CONFIG"; then
-    mkdir -p ~/.local/share/Steam
-    tar xf /etc/first-boot/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
-    echo "set_bootstrap=1" >> "$STEAM_BOOTSTRAP_CONFIG"
-fi
-
-
-# Atempt to fallback to a desktop session if something goes wrong too many times
+# Attempt to fallback to a desktop session if something goes wrong too many times
 short_session_tracker_file="/tmp/chimeraos-short-session-tracker"
 short_session_duration=60
 short_session_count_before_reset=3
@@ -243,27 +171,18 @@ SECONDS=0
 short_session_count=$(< "$short_session_tracker_file" wc -l)
 
 if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-    echo >&2 "gamescope-session: detected broken Steam or gamescope failure, will try to reset the session"
-    mkdir -p ~/.local/share/Steam
-    # remove some caches and stateful things known to cause Steam to fail to start if corrupt
-    rm -rf --one-file-system ~/.local/share/Steam/config/widevine
-    # extract the steam bootstrap to potentially fix the issue the next boot
-    if [[ -f "/etc/first-boot/bootstraplinux_ubuntu12_32.tar.xz" ]]; then
-        tar xf /etc/first-boot/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
-    fi
-    # change session to desktop as fallback
-    steamos-session-select desktop
+    echo >&2 "gamescope-session: detected broken ${CLIENT} or gamescope failure, will try to reset the session"
+
+    short_session_recover
+
     # rearm
     rm "$short_session_tracker_file"
     exit 1
 fi
 
 # Log rotate the last session
-if [ -f "${HOME}"/.steam-tweaks.log ]; then
-    cp "${HOME}"/.steam-tweaks.log "${HOME}"/.steam-tweaks.log.old
-fi
-if [ -f "${HOME}"/.steam-stdout.log ]; then
-    cp "${HOME}"/.steam-stdout.log "${HOME}"/.steam-stdout.log.old
+if [ -f "${HOME}"/.${CLIENT}-stdout.log ]; then
+    cp "${HOME}"/.${CLIENT}-stdout.log "${HOME}"/.${CLIENT}-stdout.log.old
 fi
 if [ -f "${HOME}"/.gamescope-stdout.log ]; then
     cp "${HOME}"/.gamescope-stdout.log "${HOME}"/.gamescope-stdout.log.old
@@ -289,11 +208,6 @@ else
 	# Systemd or Session manager will have to restart session
 fi
 
-# Run steam-tweaks if exists
-if command -v steam-tweaks > /dev/null; then
-    steam-tweaks > "${HOME}"/.steam-tweaks.log
-fi
-
 # Input method support if present
 if command -v /usr/bin/ibus-daemon > /dev/null; then
     /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
@@ -304,16 +218,16 @@ if command -v mangoapp > /dev/null; then
     mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1 &
 fi
 
-# If we have steam_notif_daemon binary start it
-if command -v steam_notif_daemon > /dev/null; then
-    steam_notif_daemon > "${HOME}"/.steam_notif_daemon-stdout.log 2>&1 &
+# For compatibility with older user configuration overrides
+if [ -n "$STEAMCMD" ] ; then
+	CLIENTCMD=$STEAMCMD
 fi
 
-# Start Steam client
-$STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1
+# Start client application
+$CLIENTCMD > "${HOME}/.${CLIENT}-stdout.log" 2>&1
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
-	echo "steam failed" >> "$short_session_tracker_file"
+	echo "${CLIENT} failed" >> "$short_session_tracker_file"
 else
 	rm "$short_session_tracker_file"
 fi
@@ -325,15 +239,15 @@ kill $gamescope_pid
 sleep 5 &
 sleep_pid="$!"
 
-# Catch reboot and poweroof sentinels here
-if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
+# Catch reboot and powerof sentinels here
+if [[ -e "$REBOOT_SENTINEL" ]]; then
+	rm -f "$REBOOT_SENTINEL"
 	# rearm short session tracker
 	rm "$short_session_tracker_file"
 	reboot
 fi
-if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
+if [[ -e "$SHUTDOWN_SENTINEL" ]]; then
+	rm -f "$SHUTDOWN_SENTINEL"
 	# rearm short session tracker
 	rm "$short_session_tracker_file"
 	poweroff
