Add fallback session to desktop if gamescope or steam client crashes (#24)

diff --git a/usr/share/gamescope-session/gamescope-session-script b/usr/share/gamescope-session/gamescope-session-script
--- a/usr/share/gamescope-session/gamescope-session-script
+++ b/usr/share/gamescope-session/gamescope-session-script
@@ -185,6 +185,26 @@ fi
 # Workaround for Steam login issue while Steam client change propagates out of Beta
 touch "${HOME}"/.steam/root/config/SteamAppData.vdf || true
 
+# Atempt to fallback to a desktop session if something goes wrong too many times
+short_session_tracker_file="/tmp/chimeraos-short-session-tracker"
+short_session_duration=60
+short_session_count_before_reset=3
+SECONDS=0
+
+short_session_count=$(< "$short_session_tracker_file" wc -l)
+
+if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
+    echo >&2 "gamescope-session: detected broken Steam or gamescope failure, will try to reset the session"
+    mkdir -p ~/.local/share/Steam
+    # remove some caches and stateful things known to cause Steam to fail to start if corrupt
+    rm -rf --one-file-system ~/.local/share/Steam/config/widevine
+    # change session to desktop as fallback
+    steamos-session-select desktop
+    # rearm
+    rm "$short_session_tracker_file"
+    exit 1
+fi
+
 # Log rotate the last session
 if [ -f "${HOME}"/.steam-tweaks.log ]; then
     cp "${HOME}"/.steam-tweaks.log "${HOME}"/.steam-tweaks.log.old
@@ -205,9 +225,10 @@ if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
 	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
 	# We're done!
 else
+	echo "gamescope failed" >> "$short_session_tracker_file"
 	kill -9 "$gamescope_pid"
 	wait
-	exit 0
+	exit 1
 	# Systemd or Session manager will have to restart session
 fi
 
@@ -229,6 +250,12 @@ fi
 # Start Steam client
 $STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1
 
+if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
+	echo "steam failed" >> "$short_session_tracker_file"
+else
+	rm "$short_session_tracker_file"
+fi
+
 # When the client exits, kill gamescope nicely
 kill $gamescope_pid
 
@@ -239,10 +266,14 @@ sleep_pid="$!"
 # Catch reboot and poweroof sentinels here
 if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
 	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
+	# rearm short session tracker
+	rm "$short_session_tracker_file"
 	reboot
 fi
 if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
 	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
+	# rearm short session tracker
+	rm "$short_session_tracker_file"
 	poweroff
 fi
 
