Remove external gamescope args. Add touch and bypass steam resolution args.

diff --git a/usr/share/gamescope-session-plus/gamescope-session-plus b/usr/share/gamescope-session-plus/gamescope-session-plus
--- a/usr/share/gamescope-session-plus/gamescope-session-plus
+++ b/usr/share/gamescope-session-plus/gamescope-session-plus
@@ -6,12 +6,12 @@ declare -r CLIENT_CONFIG_DIR_ETC=/etc/gamescope-session-plus/sessions.d
 declare -r CLIENT_CONFIG_DIR_LOCAL="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope-session-plus/sessions.d"
 
 # default empty session recovery function
-short_session_recover () {
+short_session_recover() {
 	:
 }
 
 # default empty function to run after gamescope is started
-post_gamescope_start () {
+post_gamescope_start() {
 	:
 }
 
@@ -54,12 +54,12 @@ export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
 # so we don't get mangoapp showing up before Steam initializes
 # on OOBE and stuff.
 mkdir -p "$(dirname "$MANGOHUD_CONFIGFILE")"
-echo "no_display" > "$MANGOHUD_CONFIGFILE"
+echo "no_display" >"$MANGOHUD_CONFIGFILE"
 
 # Prepare our initial VRS config file
 # for dynamic VRS in Mesa.
 mkdir -p "$(dirname "$RADV_FORCE_VRS_CONFIG_FILE")"
-echo "1x1" > "$RADV_FORCE_VRS_CONFIG_FILE"
+echo "1x1" >"$RADV_FORCE_VRS_CONFIG_FILE"
 
 # To expose vram info from radv
 export WINEDLLOVERRIDES=dxgi=n
@@ -77,22 +77,20 @@ ulimit -n 524288
 
 # Source device quirks if exists
 if [ -f /usr/share/gamescope-session-plus/device-quirks ]; then
-  . /usr/share/gamescope-session-plus/device-quirks
+	. /usr/share/gamescope-session-plus/device-quirks
 fi
 
 # Source client app specific configuration files
 set -a
-for i in ${CLIENT_CONFIG_DIR_USR}/${CLIENT} ${CLIENT_CONFIG_DIR_ETC}/${CLIENT} ${CLIENT_CONFIG_DIR_LOCAL}/${CLIENT} ;
-do
-    [[ -f "${i}" ]] && . "${i}"
+for i in ${CLIENT_CONFIG_DIR_USR}/${CLIENT} ${CLIENT_CONFIG_DIR_ETC}/${CLIENT} ${CLIENT_CONFIG_DIR_LOCAL}/${CLIENT}; do
+	[[ -f "${i}" ]] && . "${i}"
 done
 set +a
 
 # Source user configuration from ~/.config/environment.d
 set -a
-for i in "${HOME}"/.config/environment.d/*.conf ;
-do
-    [[ -f "${i}" ]] && . "${i}"
+for i in "${HOME}"/.config/environment.d/*.conf; do
+	[[ -f "${i}" ]] && . "${i}"
 done
 set +a
 
@@ -126,52 +124,80 @@ fi
 
 CURSOR=""
 # Use specified cursor if file exists
-if [ -f "$CURSOR_FILE" ] ; then
-    CURSOR="--cursor ${CURSOR_FILE}"
+if [ -f "$CURSOR_FILE" ]; then
+	CURSOR="--cursor ${CURSOR_FILE}"
 fi
 
 # Use specified output connector(s) if set, otherwise use default value
 : "${OUTPUT_CONNECTOR:=*,eDP-1}"
 
-if [ -z "$GAMESCOPECMD" ] ; then
-    RESOLUTION=""
-    if [ -n "$SCREEN_WIDTH" ] && [ -n "$SCREEN_HEIGHT" ] ; then
-        RESOLUTION="-W $SCREEN_WIDTH -H $SCREEN_HEIGHT"
-    fi
-    
-    if [ -z $VULKAN_ADAPTER ]; then
-        GAMESCOPECMD="/usr/bin/gamescope \
-        $CURSOR \
-        -e \
-        $RESOLUTION \
-        --xwayland-count 2 \
-        -O $OUTPUT_CONNECTOR \
-        --default-touch-mode 4 \
-        --hide-cursor-delay 3000 \
-        --fade-out-duration 200 \
-        -R $socket -T $stats"
-     else
-        GAMESCOPECMD="/usr/bin/gamescope \
-        $CURSOR \
-        -e \
-        $RESOLUTION \
-        --xwayland-count 2 \
-        -O $OUTPUT_CONNECTOR \
-        --default-touch-mode 4 \
-        --hide-cursor-delay 3000 \
-        --fade-out-duration 200 \
-        --prefer-vk-device $VULKAN_ADAPTER \
-        -R $socket -T $stats"
-     fi
+if [ -z "$GAMESCOPECMD" ]; then
+	RESOLUTION=""
+	if [ -n "$SCREEN_WIDTH" ] && [ -n "$SCREEN_HEIGHT" ]; then
+		RESOLUTION="-W $SCREEN_WIDTH -H $SCREEN_HEIGHT"
+	fi
 
+	if (gamescope --help 2>&1 | grep -e "--bypass-steam-resolution" >/dev/null); then
+		if [ -z $VULKAN_ADAPTER ]; then
+			GAMESCOPECMD="/usr/bin/gamescope \
+          $CURSOR \
+          -e \
+          $RESOLUTION \
+          --xwayland-count 2 \
+          -O $OUTPUT_CONNECTOR \
+          --default-touch-mode 4 \
+          --touch-gestures \
+          --bypass-steam-resolution \
+          --hide-cursor-delay 3000 \
+          --fade-out-duration 200 \
+          -R $socket -T $stats"
+		else
+			GAMESCOPECMD="/usr/bin/gamescope \
+          $CURSOR \
+          -e \
+          $RESOLUTION \
+          --xwayland-count 2 \
+          -O $OUTPUT_CONNECTOR \
+          --default-touch-mode 4 \
+          --touch-gestures \
+          --bypass-steam-resolution \
+          --hide-cursor-delay 3000 \
+          --fade-out-duration 200 \
+          --prefer-vk-device $VULKAN_ADAPTER \
+          -R $socket -T $stats"
+		fi
+	else
+		if [ -z $VULKAN_ADAPTER ]; then
+			GAMESCOPECMD="/usr/bin/gamescope \
+          $CURSOR \
+          -e \
+          $RESOLUTION \
+          --xwayland-count 2 \
+          -O $OUTPUT_CONNECTOR \
+          --default-touch-mode 4 \
+          --hide-cursor-delay 3000 \
+          --fade-out-duration 200 \
+          -R $socket -T $stats"
+		else
+			GAMESCOPECMD="/usr/bin/gamescope \
+          $CURSOR \
+          -e \
+          $RESOLUTION \
+          --xwayland-count 2 \
+          -O $OUTPUT_CONNECTOR \
+          --default-touch-mode 4 \
+          --prefer-vk-device $VULKAN_ADAPTER \
+          -R $socket -T $stats"
+		fi
+	fi
 else
-    # Add socket and stats read
-    if [ -z $VULKAN_ADAPTER ]; then
-        GAMESCOPECMD+=" -R $socket -T $stats"
-    else
-        GAMESCOPECMD+=" --prefer-vk-device $VULKAN_ADAPTER -R $socket -T $stats"
-    fi
-    
+	# Add socket and stats read
+	if [ -z $VULKAN_ADAPTER ]; then
+		GAMESCOPECMD+=" -R $socket -T $stats"
+	else
+		GAMESCOPECMD+=" --prefer-vk-device $VULKAN_ADAPTER -R $socket -T $stats"
+	fi
+
 fi
 
 # Attempt to fallback to a desktop session if something goes wrong too many times
@@ -180,40 +206,40 @@ short_session_duration=60
 short_session_count_before_reset=3
 SECONDS=0
 
-short_session_count=$(< "$short_session_tracker_file" wc -l)
+short_session_count=$(wc <"$short_session_tracker_file" -l)
 
 if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-    echo >&2 "gamescope-session-plus: detected broken ${CLIENT} or gamescope failure, will try to reset the session"
+	echo >&2 "gamescope-session-plus: detected broken ${CLIENT} or gamescope failure, will try to reset the session"
 
-    short_session_recover
+	short_session_recover
 
-    # rearm
-    rm "$short_session_tracker_file"
-    exit 1
+	# rearm
+	rm "$short_session_tracker_file"
+	exit 1
 fi
 
 # Log rotate the last session
 if [ -f "${HOME}"/.${CLIENT}-stdout.log ]; then
-    cp "${HOME}"/.${CLIENT}-stdout.log "${HOME}"/.${CLIENT}-stdout.log.old
+	cp "${HOME}"/.${CLIENT}-stdout.log "${HOME}"/.${CLIENT}-stdout.log.old
 fi
 if [ -f "${HOME}"/.gamescope-stdout.log ]; then
-    cp "${HOME}"/.gamescope-stdout.log "${HOME}"/.gamescope-stdout.log.old
+	cp "${HOME}"/.gamescope-stdout.log "${HOME}"/.gamescope-stdout.log.old
 fi
 if [ -f "${HOME}"/.gamescope-cmd.log ]; then
-    cp "${HOME}"/.gamescope-cmd.log "${HOME}"/.gamescope-cmd.log.old
+	cp "${HOME}"/.gamescope-cmd.log "${HOME}"/.gamescope-cmd.log.old
 fi
 
 # Start gamescope compositor, log it's output and background it
-echo $GAMESCOPECMD > "${HOME}"/.gamescope-cmd.log
-$GAMESCOPECMD > "${HOME}"/.gamescope-stdout.log 2>&1 &
+echo $GAMESCOPECMD >"${HOME}"/.gamescope-cmd.log
+$GAMESCOPECMD >"${HOME}"/.gamescope-stdout.log 2>&1 &
 gamescope_pid="$!"
 
-if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
+if read -r -t 3 response_x_display response_wl_display <>"$socket"; then
 	export DISPLAY="$response_x_display"
 	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
 	# We're done!
 else
-	echo "gamescope failed" >> "$short_session_tracker_file"
+	echo "gamescope failed" >>"$short_session_tracker_file"
 	kill -9 "$gamescope_pid"
 	wait
 	exit 1
@@ -224,27 +250,27 @@ fi
 post_gamescope_start
 
 # Input method support if present
-if command -v /usr/bin/ibus-daemon > /dev/null; then
-    /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
+if command -v /usr/bin/ibus-daemon >/dev/null; then
+	/usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
 fi
 
 # If we have mangoapp binary start it
-if command -v mangoapp > /dev/null; then
+if command -v mangoapp >/dev/null; then
 	(while true; do
-		mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1
+		mangoapp >"${HOME}"/.mangoapp-stdout.log 2>&1
 	done) &
 fi
 
 # For compatibility with older user configuration overrides
-if [ -n "$STEAMCMD" ] ; then
+if [ -n "$STEAMCMD" ]; then
 	CLIENTCMD=$STEAMCMD
 fi
 
 # Start client application
-$CLIENTCMD > "${HOME}/.${CLIENT}-stdout.log" 2>&1
+$CLIENTCMD >"${HOME}/.${CLIENT}-stdout.log" 2>&1
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
-	echo "${CLIENT} failed" >> "$short_session_tracker_file"
+	echo "${CLIENT} failed" >>"$short_session_tracker_file"
 else
 	rm "$short_session_tracker_file"
 fi
@@ -292,4 +318,3 @@ for job in $(jobs -p); do
 	fi
 	kill -9 "$job"
 done
-
